
const list = [
{song : 'Like a Rolling Stone', singer: 'Bob Dylan',	year: 1965,	genre: 'Pop'},
{song : '(I Can’t Get No) Satisfaction',	singer: 'The Rolling Stones',	year: 1965,	genre: 'Rock'},
{song : 'Imagine',	singer: 'John Lennon',	year: 1971, genre: 'Rock'},
{song : 'What’s Going On',	singer: 'Marvin Gaye',	year: 1971,	genre: 'R&B'},
{song : 'Respect',	singer: 'Aretha Franklin',	year: 1967,	genre: 'R&B'},
{song : 'Good Vibrations',	singer: 'The Beach Boys',	year: 1966,	genre: 'Rock'},
{song : 'Johnny B. Goode',	singer: 'Chuck Berry',	year: 1958,	genre: 'Rock and roll'},
{song : 'Hey Jude',	singer: 'The Beatles',	year: 1968, genre: 'Rock'},
{song : 'Smells Like Teen Spirit',	singer: 'Nirvana',	year: 1991, genre: 'Rock'},
{song : 'What’d I Say',	singer: 'Ray Charles',	year: 1959, genre: 'R&B'},
{song : 'My Generation',	singer: 'The Who',	year: 1965,	genre: 'Rock'},
{song : 'A Change Is Gonna Come',	singer: 'Sam Cooke',	year: 1964,	genre: 'Soul'},
{song : 'Yesterday',	singer: 'The Beatles',	year: 1965,	genre: 'Rock'},
{song : 'Blowin’ in the Wind',	singer: 'Bob Dylan',	year: 1963, genre: 'Pop'},
{song : 'London Calling',	singer: 'The Clash',	year: 1980, genre: '‎Punk rock'},
{song : 'I Want to Hold Your Hand',	singer: 'The Beatles',	year: 1963,	genre: 'Rock'},
{song : 'Purple Haze',	singer: 'The Jimi Hendrix Experience',	year: 1967, genre: 'Rock'},
{song : 'Maybellene',	singer: 'Chuck Berry',	year: 1955,	genre: 'Rock and roll'},
{song : 'Hound Dog',	singer: 'Elvis Presley',	year: 1956,	genre: 'Pop'},
{song : 'Let It Be',	singer: 'The Beatles',	year: 1970,	genre: 'Rock'},
{song : 'Born to Run',	singer: 'Bruce  Springsteen',	year: 1975,	genre: 'Rock'},
{song : 'Be My Baby',	singer: 'The Ronettes',	year: 1963,	genre: 'Pop'},
{song : 'In My Life',	singer: 'The Beatles',	year: 1965,	genre: 'Rock'},
{song : 'People Get Ready',	singer: 'The Impressions',	year: 1965,	genre: 'R&B'},
{song : 'God Only Knows',	singer: 'The Beach Boys',	year: 1966,	genre: 'Rock'},
{song : '(Sittin’ on) The Dock of the Bay',	singer: 'Otis Redding', year: 1968,	genre: 'Soul'},
{song : 'Layla',	singer: 'Derek and the Dominos',	year: 1970,	genre: 'R&B'},
{song : 'A Day in the Life',	singer: 'The Beatles',	year: 1967,	genre: 'Rock'},
{song : 'Help!',	singer: 'The Beatles',	year: 1965,	genre: 'Rock'},
{song : 'I Walk the Line',	singer: 'Johnny Cash',	year: 1956,	genre: 'Country'},
{song : 'Stairway to Heaven',	singer: 'Led Zeppelin',	year: 1971,	genre: 'Rock'},
{song : 'Sympathy for the Devil',	singer: 'The Rolling Stones',	year: 1968,	genre: 'Rock'},
{song : 'River Deep – Mountain High',	singer: 'Ike Turner и Tina Turner',	year: 1966,	genre: 'R&B'},
{song : 'You’ve Lost That Lovin’ Feelin’',	singer: 'The Righteous Brothers',	year: 1964,	genre: 'Pop'},
{song : 'Light My Fire',	singer: 'The Doors',	year: 1967,	genre: 'Rock'},
{song : 'One',	singer: 'U2',	year: 1992,	genre: 'Rock'},
{song : 'No Woman, No Cry',	singer: 'Bob Marley and The Wailers',	year: 1975, genre: 'Reggae' },
{song : 'Gimme Shelter',	singer: 'The Rolling Stones',	year: 1969,	genre: 'Rock'},
{song : 'That’ll Be the Day',	singer: 'Buddy Holly and The Crickets',	year: 1957,	genre: 'Rock and roll'},
{song : 'Dancing in the Street',	singer: 'Martha and the Vandellas',	year: 1964,	genre: 'R&B'},
{song : 'The Weight',	singer: 'The Band',	year: 1968,	genre: 'Folk rock'},
{song : 'Waterloo Sunset',	singer: 'The Kinks',	year: 1968,	genre: 'Rock'},
{song : 'Tutti Frutti',	singer: 'Little Richard',	year: 1955,	genre: 'Rock and roll'	},
{song : 'Georgia on My Mind',	singer: 'Ray Charles',	year: 1960,	genre: 'R&B'},
{song : 'Heartbreak Hotel',	singer: 'Elvis Presley',	year: 1956,	genre: 'Pop'},
{song : 'Heroes',	singer: 'David Bowie',	year: 1977,	genre: 'Rock'},
{song : 'All Along the Watchtower',	singer: 'The Jimi Hendrix Experience',	year: 1968,	genre: 'Rock'},
{song : 'Bridge Over Troubled Water',	singer: 'Simon and Garfunkel',	year: 1970,	genre: 'Pop'},
{song : 'Hotel California',	singer: 'The Eagles',	year: 1976,	genre: 'Rock'},
{song : 'The Tracks of My Tears',	singer: 'Smokey Robinson and The Miracles',	year: 1965,	genre: 'Pop'},
{song : 'The Message	Grandmaster', singer: 'Flash and the Furious Five',	year: 1982,	genre: 'Hip hop'},
{song : 'When Doves Cry',	singer: 'Prince' ,	year: 1984,	genre: 'Pop'},
{song : 'When a Man Loves a Woman',	singer: 'Percy Sledge', year: 1966,	genre: 'Pop'},
{song : 'Louie Louie',	singer: 'The Kingsmen',	year: 1963,	genre: 'Rock'},
{song : 'Long Tall Sally',	singer: 'Little Richard',	year: 1956,	genre: 'Rock and roll'},
{song : 'Anarchy in the UK',	singer: 'The Sex Pistols',	year: 1977,	genre: 'Punk rock'},
{song : 'A Whiter Shade of Pale',	singer: 'Procol Harum',	year: 1967,	genre: 'Rock'},
{song : 'Billie Jean',	singer: 'Michael Jackson',	year: 1983,	genre: 'Pop'},
{song : 'The Times They Are a-Changin',	singer: 'Bob Dylan',	year: 1964, genre: 'Pop'},
{song : 'Let’s Stay Together',	singer: 'Al Green',	year: 1971,	genre: 'R&B'},
{song : 'Whole Lotta Shakin’ Goin’ On',	singer: 'Jerry Lee Lewis',	year: 1957,	genre: 'Rock and roll'},
{song : 'Bo Diddley',	singer: 'Bo Diddley',	year: 1955,	genre: 'Rock and roll'},
{song : 'For What It’s Worth',	singer: 'Buffalo Springfield',	year: 1967,	genre: 'Folk rock'},
{song : 'She Loves You',	singer: 'The Beatles',	year: 1963, genre: 'Rock'},
{song : 'Sunshine of Your Love',	singer: 'Cream',	year: 1968,	genre: 'Rock'},
{song : 'Redemption Song',	singer: 'Bob Marley and The Wailers',	year: 1980,	genre: 'Reggae'},
{song : 'Jailhouse Rock',	singer: 'Elvis Presley',	year: 1957,	genre: 'Pop'},
{song : 'Tangled Up in Blue',	singer: 'Bob Dylan',	year: 1975,	genre: 'Pop'},
{song : 'Crying',	singer: 'Roy Orbison',	year: 1961,	genre: 'Rock and roll'},
{song : 'Walk On By',	singer: 'Dionne Warwick',	year: 1964, genre: 'Pop'},
{song : 'Papa’s Got a Brand New Bag',	singer: 'James Brown',	year: 1966,	 genre: 'Pop'},
{song : 'California Girls',	singer: 'The Beach Boys',	year: 1965,	genre: 'Rock'},
{song : 'Superstition',	singer: 'Stevie Wonder',	year: 1972,	genre: 'Soul'},
{song : 'Summertime Blues',	singer: 'Eddie Cochran',	year: 1958,	genre: 'Rock and roll'},
{song : 'Whole Lotta Love',	singer: 'Led Zeppelin',	year: 1969,	genre: 'Rock'},
{song : 'Strawberry Fields Forever',	singer: 'The Beatles',	year: 1967,	genre: 'Rock'},
{song : 'Mystery Train',	singer: 'Elvis Presley',	year: 1955, genre: 'Pop'},
{song : 'I Got You (I Feel Good)',	singer: 'James Brown',	year: 1965, genre: 'Pop'},
{song : 'Mr. Tambourine Man',	singer: 'The Byrds',	year: 1965,	genre: 'Rock'},
{song : 'You Really Got Me',	singer: 'The Kinks',	year: 1964,	genre: 'Rock'},
{song : 'I Heard It Through the Grapevine',	singer: 'Marvin Gaye',	year: 1968,	genre: 'Pop'},
{song : 'Blueberry Hill',	singer: 'Fats Domino',	year: 1956,	genre: 'Rock and roll'},
{song : 'Norwegian Wood (This Bird Has Flown)',	singer: 'The Beatles',	year: 1965,	genre: 'Rock'},
{song : 'Every Breath You Take',	singer: 'The Police',	year: 1983,	genre: 'Rock'},
{song : 'Crazy',	singer: 'Patsy Cline', year: 1961,	genre: 'Pop'},
{song : 'Thunder Road',	singer: 'Bruce Springsteen',	year: 1975, genre: 'Rock'},
{song : 'Ring of Fire',	singer: 'Johnny Cash',	year: 1963,	genre: 'Country'},
{song : 'My Girl',	singer: 'The Temptations',	year: 1965,	genre: 'Pop'},
{song : 'California Dreamin',	singer: 'The Mamas and The Papas',	year: 1965,	genre: 'Pop'},
{song : 'In the Still of the Night',	singer: 'The Five Satins',	year: 1956, genre: 'Pop'},
{song : 'Suspicious Minds',	singer: 'Elvis Presley',	year: 1969,	genre: 'Pop'},
{song : 'Blitzkrieg Bop',	singer: 'Ramones',	year: 1976,	genre: 'Punk rock'},
{song : 'I Still Haven’t Found What I’m Looking For',	singer: 'U2',	year: 1987,	genre: 'Rock'},
{song : 'Good Golly Miss Molly',	singer: 'Little Richard',	year: 1958,	genre: 'Rock and roll'},
{song : 'Blue Suede Shoes',	singer: 'Carl Perkins',	year: 1956,	genre: 'Rock and roll'},
{song : 'Great Balls of Fire',	singer: 'Jerry Lee Lewis', year:	1957,	genre: 'Rock and roll'},
{song : 'Roll Over Beethoven',	singer: 'Chuck Berry',	year: 1956, genre: 'Rock and roll'},
{song : 'Love and Happiness',	singer: 'Al Green',	year: 1972,	genre: 'R&B'},
{song : 'Fortunate Son',	singer: 'Creedence Clearwater Revival',	year: 1969,	genre: 'Rock'},
{song : 'Crazy',	singer: 'Gnarls Barkley',	year: 2006,	genre: 'Soul'}
]

export default list
